# Generated by Django 2.0.6 on 2018-06-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branchcode', models.IntegerField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('branchname', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('acctid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=45)),
                ('lname', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=300)),
                ('contactnum', models.CharField(max_length=45)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='client.Branch')),
            ],
        ),
    ]
