# Generated by Django 2.0.6 on 2018-06-27 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branchcode',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
